# Generated by Django 3.1.7 on 2021-05-21 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='service_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Specify Service')),
            ],
        ),
        migrations.CreateModel(
            name='mypost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=264, verbose_name='Enter Post Title')),
                ('slug', models.SlugField(max_length=264, unique=True)),
                ('City', models.CharField(max_length=264, verbose_name='Enter Your City')),
                ('Full_Adress', models.CharField(max_length=264, verbose_name='Enter Full adress')),
                ('phone_number', models.IntegerField(max_length=10)),
                ('post_text', models.TextField(verbose_name='Write about your requirement/service here')),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('service_provider', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_author', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-publish_date'],
            },
        ),
    ]
