# Generated by Django 3.1.7 on 2021-06-01 16:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20210601_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypost',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only 0-9 are allowed!')]),
        ),
    ]
